### ISSUE TITLE
Missing the parameter X for W_metric?

### ISSUE THREAD

**Issue by cquxl** [pprp/Pruner-Zero#6]
In prune.py, find out if W_metric is missing X,should it be engine.forward(W,G,X)?

![1722996516687](https://github.com/user-attachments/assets/12fb8cbe-9f2b-45ce-aa79-2d4d38adfe53)

**Comment by pprp** [comment]
In fact, these code is only used for inference, which is correspond to the equation found in our paper. 

As you can see, X is just part of the search space, and we actually have tried it before. If you want to search further, you can modify the `forward` function of engine to incorporate the X.

**Comment by cquxl** [comment]
But your _**engine.forward**_ has 3 arguments, W,G,X. Do you mean I need to modify the forward function, i.e. remove X? Because I get an error when running your code directly: TypeError: GPTree.forward() missing 1 required positional argument: 'X'. If engine.forward only has two arguments, would it be best to clarify this on github so we can get fair and correct results?

**Comment by lybbill** [comment]
same problem I encouter !

**Comment by hhhhain** [comment]
same problem

**Comment by pprp** [comment]
Thanks for you caring. I have fixed the code in https://github.com/pprp/Pruner-Zero/commit/db70134ed7d4c521a57060fd698f353d04268429. 

Please let me know if there are any further bugs.
